# Generated by Django 4.1.3 on 2023-01-17 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epic_events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='customer',
        ),
        migrations.AddField(
            model_name='event',
            name='contract',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='event_contract', to='epic_events.contract'),
        ),
        migrations.AlterField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_support_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
